parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Doctrine\TiDBSSLMiddleware:
        arguments:
            $sslCa: '%env(default::DB_SSL_CA)%'
        tags:
            - { name: doctrine.middleware }
